spring:
  profiles:
    active: local
---
spring:
  profile: local

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

url:
  users: http://localhost:7071
  items: http://localhost:7072
